### PR TITLE
Fixes #39: Wrong GCS bucket name

### LINKED ISSUE #39: GCS bucket name
There a reason that the `cluster_name` variable is used in favour of the aptly named `gcs_bucket_name` one?
https://github.com/hashicorp/terraform-google-vault/blob/70e8e8d8b6ca66e4dfe2ab875afa73de33955062/modules/vault-cluster/main.tf#L278

### PR DESCRIPTION
**Pull request by robmorgan**
Relevant issue #39.

### CODE REVIEW

**Comment by Eoino** [comment]
Possibly need to modify the following also, I'm guessing? Not sure if there are any others.
https://github.com/hashicorp/terraform-google-vault/blob/07b2996798d3d5da177084421492f5ac73f946f4/modules/vault-cluster/main.tf#L299
https://github.com/hashicorp/terraform-google-vault/blob/07b2996798d3d5da177084421492f5ac73f946f4/modules/vault-cluster/main.tf#L312

**Comment by robmorgan** [comment]
@Eoino yep, definitely will. I guess we could probably use `"${google_storage_bucket.vault_storage_backend.name}"` here.

**Comment by Etiene** [comment]
For some reason I cant see the job on circle ci, I guess you need to sign the contributor agreement first...

Another question, is this change backwards compatible?

**Comment by robmorgan** [comment]
Hi @Etiene, I've signed the CLA now. Yeah, I think the reason you can't see the build on CircleCI is because the branch is under my account - `robmorgan`. So you can either pull the branch across to the Hashicorp org somehow to trigger a build or merge it.

Yes its definitely **not backwards compatible**. It would destroy an existing bucket and attempt to create a new one. We could address this in the release notes or tell users to ensure `${var.gcs_bucket_name}` has the same value as `${var.cluster_name}"`. That wouldn't trigger a change.

WDYT?

**Comment by Etiene** [comment]
What about doing something like this?
`name  = "${var.gcs_bucket_name == "" ? var.cluster_name : var.gcs_bucket_name}"`

**Comment by Etiene** [comment]
ping

**Comment by robmorgan** [comment]
Hey @Etiene, I've improved the code and docs a bit. Also, I've tested locally and I don't get a diff in the plan anymore between the `master` version and this branch. Therefore it should no longer be considered a breaking change.

Please merge + release when you're happy.

**Pull request merged**
